apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: test-alert
  namespace: monitoring
  labels:
    release: prometheus
spec:
  groups:
    - name: test.rules
      rules:
        - alert: AlwaysFiring
          expr: vector(1)
          for: 10s
          labels:
            severity: warning
          annotations:
            summary: "Test Alert"
            description: "This is a test alert to verify email sending"
