{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: servicemonitor
  namespace: monitoring
  labels:
    release: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: spring-boot-app
  endpoints:
    - path: {{ .Values.serviceMonitor.path }}
      port: {{ .Values.service.portName | default "http" }}
      interval: {{ .Values.serviceMonitor.interval }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
{{- end }}
