apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: spring-boot-app-servicemonitor
  labels:
    release: prometheus  
spec:
  selector:
    matchLabels:
      app: spring-boot-app 
  namespaceSelector:
    matchNames:
      - {{ .Values.namespace }} 
  endpoints:
    - port: {{ .Values.portName }} metricsPath
      path: {{ .Values.metricsPath }}
      interval: 15s
