apiVersion: v1
kind: Service
metadata:
  name: spring-boot-app-service
spec:
  type: {{ .Values.service.type }}
  selector:
    app: spring-boot-app
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}
