apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: jenkins-servicemonitor-access
rules:
  - apiGroups:
      - monitoring.coreos.com
    resources:
      - servicemonitors
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: jenkins-servicemonitor-access-binding
subjects:
  - kind: ServiceAccount
    name: jenkins
    namespace: springboot-namespace
roleRef:
  kind: ClusterRole
  name: jenkins-servicemonitor-access
  apiGroup: rbac.authorization.k8s.io
